name: swiftclub
description: An app built using Flutter for web

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: 0.15.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.7.0
  html: 0.14.0+2
  http: 0.12.0+2
  js: 0.6.1+1
  universal_html: ^1.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/swift_logo.png
